//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG7312ST10202241.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROG7312ST10202241.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Image Or Document.
        /// </summary>
        internal static string AttachImageOrDocument {
            get {
                return ResourceManager.GetString("AttachImageOrDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach Media.
        /// </summary>
        internal static string AttachMediaBtn {
            get {
                return ResourceManager.GetString("AttachMediaBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments Added:.
        /// </summary>
        internal static string AttachmentsAdded {
            get {
                return ResourceManager.GetString("AttachmentsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To Main Menu.
        /// </summary>
        internal static string BackToMainMenuBtn {
            get {
                return ResourceManager.GetString("BackToMainMenuBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Login.
        /// </summary>
        internal static string btnEmployeeLogin {
            get {
                return ResourceManager.GetString("btnEmployeeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Category.
        /// </summary>
        internal static string btnSearchByCategory {
            get {
                return ResourceManager.GetString("btnSearchByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by Date.
        /// </summary>
        internal static string btnSearchByDate {
            get {
                return ResourceManager.GetString("btnSearchByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search With All Criteria.
        /// </summary>
        internal static string btnSearchWithAll {
            get {
                return ResourceManager.GetString("btnSearchWithAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Status .
        /// </summary>
        internal static string btnUpdateStatus {
            get {
                return ResourceManager.GetString("btnUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryLbl {
            get {
                return ResourceManager.GetString("CategoryLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roads.
        /// </summary>
        internal static string CategoryRoads {
            get {
                return ResourceManager.GetString("CategoryRoads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sanitation.
        /// </summary>
        internal static string CategorySanitation {
            get {
                return ResourceManager.GetString("CategorySanitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        internal static string CategoryUtilities {
            get {
                return ResourceManager.GetString("CategoryUtilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close.
        /// </summary>
        internal static string closeBtn {
            get {
                return ResourceManager.GetString("closeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string dateLbl {
            get {
                return ResourceManager.GetString("dateLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string descriptionLbl {
            get {
                return ResourceManager.GetString("descriptionLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach media. .
        /// </summary>
        internal static string ErrorAttachMedia {
            get {
                return ResourceManager.GetString("ErrorAttachMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a category..
        /// </summary>
        internal static string ErrorEnterCategory {
            get {
                return ResourceManager.GetString("ErrorEnterCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a description..
        /// </summary>
        internal static string ErrorEnterDescription {
            get {
                return ResourceManager.GetString("ErrorEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a location..
        /// </summary>
        internal static string ErrorEnterLocation {
            get {
                return ResourceManager.GetString("ErrorEnterLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string Form1Title {
            get {
                return ResourceManager.GetString("Form1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid numeric ID. .
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue Reported Successfully!.
        /// </summary>
        internal static string IssueReportedSuccessfully {
            get {
                return ResourceManager.GetString("IssueReportedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Login.
        /// </summary>
        internal static string lblEmployeeLogin {
            get {
                return ResourceManager.GetString("lblEmployeeLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Status: .
        /// </summary>
        internal static string lblNewStatus {
            get {
                return ResourceManager.GetString("lblNewStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search ID: .
        /// </summary>
        internal static string lblSearchId {
            get {
                return ResourceManager.GetString("lblSearchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string lblUsername {
            get {
                return ResourceManager.GetString("lblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the South African Municipality Service App.
        /// </summary>
        internal static string lblWelcome {
            get {
                return ResourceManager.GetString("lblWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Events And Announcements.
        /// </summary>
        internal static string LocalEventsAndAnnouncements {
            get {
                return ResourceManager.GetString("LocalEventsAndAnnouncements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Events And Announcements.
        /// </summary>
        internal static string LocalEventsAndAnnouncementsTitle {
            get {
                return ResourceManager.GetString("LocalEventsAndAnnouncementsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location.
        /// </summary>
        internal static string locationLbl {
            get {
                return ResourceManager.GetString("locationLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string LoginFailureMessage {
            get {
                return ResourceManager.GetString("LoginFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string LoginFailureTitle {
            get {
                return ResourceManager.GetString("LoginFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string LoginSuccessMessage {
            get {
                return ResourceManager.GetString("LoginSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string LoginSuccessTitle {
            get {
                return ResourceManager.GetString("LoginSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of Event:.
        /// </summary>
        internal static string nameOfEventLbl {
            get {
                return ResourceManager.GetString("nameOfEventLbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected.
        /// </summary>
        internal static string Nofileselected {
            get {
                return ResourceManager.GetString("Nofileselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file selected for removal. .
        /// </summary>
        internal static string NoFileSelectedForRemoval {
            get {
                return ResourceManager.GetString("NoFileSelectedForRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Category.
        /// </summary>
        internal static string PleaseEnterACategory {
            get {
                return ResourceManager.GetString("PleaseEnterACategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Description .
        /// </summary>
        internal static string PleaseEnterADescription {
            get {
                return ResourceManager.GetString("PleaseEnterADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter A Location.
        /// </summary>
        internal static string PleaseEnterALocation {
            get {
                return ResourceManager.GetString("PleaseEnterALocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed: .
        /// </summary>
        internal static string Removed {
            get {
                return ResourceManager.GetString("Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Media.
        /// </summary>
        internal static string RemoveFileBtn {
            get {
                return ResourceManager.GetString("RemoveFileBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issues.
        /// </summary>
        internal static string ReportIssuesBtn {
            get {
                return ResourceManager.GetString("ReportIssuesBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Issues .
        /// </summary>
        internal static string ReportIssuesTitle {
            get {
                return ResourceManager.GetString("ReportIssuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search By Name.
        /// </summary>
        internal static string searchBtn {
            get {
                return ResourceManager.GetString("searchBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Found .
        /// </summary>
        internal static string ServiceRequestFound {
            get {
                return ResourceManager.GetString("ServiceRequestFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request with ID {id} not found. .
        /// </summary>
        internal static string ServiceRequestNotFound {
            get {
                return ResourceManager.GetString("ServiceRequestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request Status.
        /// </summary>
        internal static string ServiceRequestStatusBtn {
            get {
                return ResourceManager.GetString("ServiceRequestStatusBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string SubmitBtn {
            get {
                return ResourceManager.GetString("SubmitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reports.
        /// </summary>
        internal static string ViewReportsFormBtn {
            get {
                return ResourceManager.GetString("ViewReportsFormBtn", resourceCulture);
            }
        }
    }
}
